import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home</h1>
        <Link className="link" href="/useEffectOne">useEffectOne</Link>
        <Link className="link" href="/useEffectTwo">useEffectTwo</Link>
        <Link className="link" href="/useEffectThree">useEffectThree</Link>
        <Link className="link" href="/carouselPage">carouselPage</Link>
      </main>
    </>
  )
}
